### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by trinidadmartin** [GooglingTheCancerGenome/sv-callers#70] opened 2021-09-07 08:53 UTC
Hello!!

Trying to execute the workflow with single experiment but it fails... Anywhere where I could see any other example of execution??? I have done

`snakemake -C echo_run=1 mode=s enable_callers="['manta','delly','lumpy','gridss']" --use-conda --latency-wait 30 --jobs 14 --cluster "xenon scheduler $SCH --location local:// submit --name smk.{rule} --inherit-env --cores-per-task {threads} --max-run-time 1 --max-memory {resources.mem_mb} --working-directory . --stderr stderr-%j.log --stdout stdout-%j.log" &>smk.log&`

And if I check the job
`xenon --json scheduler $SCH --location local:// list --identifier [15958] | jq ...`
jq: error: Invalid numeric literal at EOF at line 1, column 3 (while parsing '...') at <top-level>, line 1:
...
jq: 1 compile error
local adaptor: Interactive job failed to start!

**Comment by arnikz** [comment] 2021-09-07 10:55
Hi,

First, let's make sure that your workflow runs locally with the test data as provided (follow the [README](https://github.com/GooglingTheCancerGenome/sv-callers/blob/master/README.md), step 1,2 and 4) before querying job accounting info on a compute cluster. The following commands should output something similar for you:

```
$ snakemake -np
...
[Tue Sep  7 12:27:50 2021]
localrule all:
    input: data/bam/3/T3--N3/all.vcf
    jobid: 0
    resources: tmpdir=/tmp

Job stats:
job                count    min threads    max threads
---------------  -------  -------------  -------------
all                    1              1              1
delly_merge            1              1              1
delly_p                5              1              1
gridss_p               1              1              1
lumpy_p                1              1              1
manta_p                1              1              1
survivor_filter        4              1              1
survivor_merge         1              1              1
total                 15              1              1

This was a dry-run (flag -n). The order of jobs does not reflect the order of execution.
```
```
$ snakemake -C echo_run=0 --use-conda -j
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job                count    min threads    max threads
---------------  -------  -------------  -------------
all                    1              1              1
delly_merge            1              1              1
delly_p                5              2              2
gridss_p               1              4              4
lumpy_p                1              1              1
manta_p                1              4              4
survivor_filter        4              1              1
survivor_merge         1              1              1
total                 15              1              4

Select jobs to execute...

[Tue Sep  7 12:42:10 2021]
rule delly_p:
    input: data/fasta/chr22.fasta, data/fasta/chr22.fasta.fai, data/bam/3/T3.bam, data/bam/3/T3.bam.bai, data/bam/3/N3.bam, data/bam/3/N3.bam.bai
    output: data/bam/3/T3--N3/delly_out/delly-INS.bcf
    jobid: 9
    wildcards: path=data/bam/3, tumor=T3, normal=N3, sv_type=INS
    threads: 2
    resources: tmpdir=/tmp, mem_mb=8192, tmp_mb=0
...
[Tue Sep  7 12:41:18 2021]
Finished job 0.
15 of 15 steps (100%) done
Complete log: /home/arnikz/Downloads/repos/sv-callers/snakemake/.snakemake/log/2021-09-07T123959.196498.snakemake.log
```

If the local run was successful, you can proceed with submitting jobs to an HPC cluster and then query job info:

> xenon --json scheduler $SCH --location local:// list --identifier [15958] | jq ...

where `[15958] ` should be `15958` (INT) and some `jq ...` [expression](https://stedolan.github.io/jq/manual/#Basicfilters) (e.g., `.`)

**Comment by trinidadmartin** [comment] 2021-09-07 11:38
Hi!! Thanks for the super fast reply ;)

These are my outputs:

`snakemake -np`

Building DAG of jobs...
Job counts:
	count	jobs
	1	all
	1

[Tue Sep  7 13:35:09 2021]
localrule all:
    jobid: 0

Job counts:
	count	jobs
	1	all
	1
This was a dry-run (flag -n). The order of jobs does not reflect the order of execution.

And 
`snakemake -C echo_run=1`

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1

[Tue Sep  7 13:38:00 2021]
localrule all:
    jobid: 0

[Tue Sep  7 13:38:00 2021]
Finished job 0.
1 of 1 steps (100%) done
Complete log: /Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/snakemake/.snakemake/log/2021-09-07T133800.454169.snakemake.log

**Comment by arnikz** [comment] 2021-09-07 13:56
Given the partial output above, I'm no sure if it worked for you😉

**Comment by trinidadmartin** [comment] 2021-09-07 14:19
Yeah I know... :( 
I just added my own bams and fasta files

├── ENCFF001TDO.bed
├── bam
│   ├── 1
│   │   ├── N1.bai
│   │   ├── N1.bam
│   │   ├── N1.bam.bai
│   │   ├── T1.bai
│   │   ├── T1.bam
│   │   └── T1.bam.bai
│   ├── 10C
│   │   ├── 10C.bam
│   │   └── 10C.bam.bai
│   ├── 2
│   │   ├── N2.bai
│   │   ├── N2.bam
│   │   ├── N2.bam.bai
│   │   ├── T2.1.bai
│   │   ├── T2.1.bam
│   │   ├── T2.1.bam.bai
│   │   ├── T2.2.bai
│   │   ├── T2.2.bam
│   │   └── T2.2.bam.bai
│   ├── 3
│   │   ├── N3.bam -> chr22_2.bam
│   │   ├── N3.bam.bai -> chr22_2.bam.bai
│   │   ├── T3.bam -> chr22_1.bam
│   │   ├── T3.bam.bai -> chr22_1.bam.bai
│   │   ├── chr22_1.bam
│   │   ├── chr22_1.bam.bai
│   │   ├── chr22_2.bam
│   │   └── chr22_2.bam.bai
│   └── 7B
│       ├── 7B.bam
│       └── 7B.bam.bai
└── fasta
    ├── Homo_sapiens.GRCh37.GATK.illumina.fasta
    ├── Homo_sapiens.GRCh37.GATK.illumina.fasta.amb
    ├── Homo_sapiens.GRCh37.GATK.illumina.fasta.ann
    ├── Homo_sapiens.GRCh37.GATK.illumina.fasta.bwt
    ├── Homo_sapiens.GRCh37.GATK.illumina.fasta.fai
    ├── Homo_sapiens.GRCh37.GATK.illumina.fasta.pac
    ├── Homo_sapiens.GRCh37.GATK.illumina.fasta.sa
    ├── S288C_genome.fasta
    ├── S288C_genome.fasta.amb
    ├── S288C_genome.fasta.ann
    ├── S288C_genome.fasta.bwt
    ├── S288C_genome.fasta.fai
    ├── S288C_genome.fasta.pac
    ├── S288C_genome.fasta.sa
    ├── chr22.fasta
    ├── chr22.fasta.amb
    ├── chr22.fasta.ann
    ├── chr22.fasta.bwt
    ├── chr22.fasta.dict
    ├── chr22.fasta.fai
    ├── chr22.fasta.pac
    └── chr22.fasta.sa

Changed the analysis.yaml here:
**(s)ingle-sample or (p)aired-samples analysis**
mode: s

**filepath of the reference genome in FASTA format**
genome: data/fasta/S288C_genome.fasta

**filepath of the exclusion list in BED format**
exclusion_list: data/ENCFF001TDO.bed
exclude_regions: 0 # use the list (1) or don't (0)


And modify the samples.csv :
PATH,SAMPLE1
#data/bam/7B,7B
#data/bam/10C,10C

What am I missing??
Thanks a lot!!!

**Comment by arnikz** [comment] 2021-09-07 14:23
Remove `#` from the lines.
```
PATH,SAMPLE1
#data/bam/7B,7B
#data/bam/10C,10C
```

**Comment by trinidadmartin** [comment] 2021-09-07 14:31
Of course :')

Now is doing a lot more... Here you are a bit of the output, but still same problem when running real job:

Building DAG of jobs...
Error: Directory cannot be locked. This usually means that another Snakemake instance is running on this directory. Another possibility is that a previous run exited unexpectedly.
Job counts:
	count	jobs
	1	all
	2	delly_merge
	10	delly_s
	2	gridss_s
	2	lumpy_s
	2	manta_s
	8	survivor_filter
	2	survivor_merge
	29

[Tue Sep  7 16:27:45 2021]
rule manta_s:
    input: data/fasta/S288C_genome.fasta, data/fasta/S288C_genome.fasta.fai, data/bam/10C/10C.bam, data/bam/10C/10C.bam.bai
    output: data/bam/10C/10C/manta_out/manta.vcf
    jobid: 11
    wildcards: path=data/bam/10C, sample=10C
    threads: 4
    resources: mem_mb=16384, tmp_mb=0


        set -x

        OUTDIR="$(dirname "data/bam/10C/10C/manta_out/manta.vcf")"
        OUTFILE="$(basename "data/bam/10C/10C/manta_out/manta.vcf")"

        # run dummy or real job
        if [ "1" -eq "1" ]; then
            echo "data/fasta/S288C_genome.fasta data/fasta/S288C_genome.fasta.fai data/bam/10C/10C.bam data/bam/10C/10C.bam.bai" > "data/bam/10C/10C/manta_out/manta.vcf"
        else
            configManta.py                 --runDir "${OUTDIR}"                 --reference "data/fasta/S288C_genome.fasta"                 --bam "data/bam/10C/10C.bam" &&
            cd "${OUTDIR}" &&
            ./runWorkflow.py                 --quiet                 -m local                 -j 4 &&
            # SV quality filtering
            bcftools filter                 -O v `# uncompressed VCF format`                 -o "${OUTFILE}"                 -i "FILTER == 'PASS'"                 "results/variants/diploidSV.vcf.gz"
        fi
        

[Tue Sep  7 16:27:45 2021]
rule delly_s:
    input: data/fasta/S288C_genome.fasta, data/fasta/S288C_genome.fasta.fai, data/bam/10C/10C.bam, data/bam/10C/10C.bam.bai
    output: data/bam/10C/10C/delly_out/delly-BND.bcf
    jobid: 19
    wildcards: path=data/bam/10C, sample=10C, sv_type=BND
    resources: mem_mb=8192, tmp_mb=0


        set -x

        OUTDIR="$(dirname "data/bam/10C/10C/delly_out/delly-BND.bcf")"
        PREFIX="$(basename "data/bam/10C/10C/delly_out/delly-BND.bcf" .bcf)"
        OUTFILE="${OUTDIR}/${PREFIX}.unfiltered.bcf"

        # run dummy or real job
        if [ "1" -eq "1" ]; then
            echo "data/fasta/S288C_genome.fasta data/fasta/S288C_genome.fasta.fai data/bam/10C/10C.bam data/bam/10C/10C.bam.bai" > "data/bam/10C/10C/delly_out/delly-BND.bcf"
        else
            # use OpenMP for threaded jobs
            export OMP_NUM_THREADS=1

            # SV calling
            delly call                 -t "BND"                 -g "data/fasta/S288C_genome.fasta"                 -o "${OUTFILE}"                 -q 1 `# min.paired-end mapping quality`                 -s 9 `# insert size cutoff, DELs only`                                  "data/bam/10C/10C.bam" &&
            # SV quality filtering
            bcftools filter                 -O b `# compressed BCF format`                 -o "data/bam/10C/10C/delly_out/delly-BND.bcf"                 -i "FILTER == 'PASS'"                 "${OUTFILE}" &&
            # index BCF file
            bcftools index "data/bam/10C/10C/delly_out/delly-BND.bcf"
        fi
        

[Tue Sep  7 16:27:45 2021]
rule delly_s:
    input: data/fasta/S288C_genome.fasta, data/fasta/S288C_genome.fasta.fai, data/bam/10C/10C.bam, data/bam/10C/10C.bam.bai
    output: data/bam/10C/10C/delly_out/delly-DUP.bcf
    jobid: 21
    wildcards: path=data/bam/10C, sample=10C, sv_type=DUP
    resources: mem_mb=8192, tmp_mb=0


        set -x

        OUTDIR="$(dirname "data/bam/10C/10C/delly_out/delly-DUP.bcf")"
        PREFIX="$(basename "data/bam/10C/10C/delly_out/delly-DUP.bcf" .bcf)"
        OUTFILE="${OUTDIR}/${PREFIX}.unfiltered.bcf"

        # run dummy or real job
        if [ "1" -eq "1" ]; then
            echo "data/fasta/S288C_genome.fasta data/fasta/S288C_genome.fasta.fai data/bam/10C/10C.bam data/bam/10C/10C.bam.bai" > "data/bam/10C/10C/delly_out/delly-DUP.bcf"
        else
            # use OpenMP for threaded jobs
            export OMP_NUM_THREADS=1

            # SV calling
            delly call                 -t "DUP"                 -g "data/fasta/S288C_genome.fasta"                 -o "${OUTFILE}"                 -q 1 `# min.paired-end mapping quality`                 -s 9 `# insert size cutoff, DELs only`                                  "data/bam/10C/10C.bam" &&
            # SV quality filtering
            bcftools filter                 -O b `# compressed BCF format`                 -o "data/bam/10C/10C/delly_out/delly-DUP.bcf"                 -i "FILTER == 'PASS'"                 "${OUTFILE}" &&
            # index BCF file
            bcftools index "data/bam/10C/10C/delly_out/delly-DUP.bcf"
        fi
        

[Tue Sep  7 16:27:45 2021]
rule delly_s:
    input: data/fasta/S288C_genome.fasta, data/fasta/S288C_genome.fasta.fai, data/bam/7B/7B.bam, data/bam/7B/7B.bam.bai
    output: data/bam/7B/7B/delly_out/delly-INS.bcf
    jobid: 27
    wildcards: path=data/bam/7B, sample=7B, sv_type=INS
    resources: mem_mb=8192, tmp_mb=0


        set -x

        OUTDIR="$(dirname "data/bam/7B/7B/delly_out/delly-INS.bcf")"
        PREFIX="$(basename "data/bam/7B/7B/delly_out/delly-INS.bcf" .bcf)"
        OUTFILE="${OUTDIR}/${PREFIX}.unfiltered.bcf"

        # run dummy or real job
        if [ "1" -eq "1" ]; then
            echo "data/fasta/S288C_genome.fasta data/fasta/S288C_genome.fasta.fai data/bam/7B/7B.bam data/bam/7B/7B.bam.bai" > "data/bam/7B/7B/delly_out/delly-INS.bcf"
        else
            # use OpenMP for threaded jobs
            export OMP_NUM_THREADS=1

            # SV calling
            delly call                 -t "INS"                 -g "data/fasta/S288C_genome.fasta"                 -o "${OUTFILE}"                 -q 1 `# min.paired-end mapping quality`                 -s 9 `# insert size cutoff, DELs only`                                  "data/bam/7B/7B.bam" &&
            # SV quality filtering
            bcftools filter                 -O b `# compressed BCF format`                 -o "data/bam/7B/7B/delly_out/delly-INS.bcf"                 -i "FILTER == 'PASS'"                 "${OUTFILE}" &&
            # index BCF file
            bcftools index "data/bam/7B/7B/delly_out/delly-INS.bcf"
        fi

**Comment by arnikz** [comment] 2021-09-07 14:44
First, clean-up and then re-run the workflow. Please include your `snakemake` command-line.

```
snakemake --unlock
rm -r data/bam/10C/10C/*_out
rm -r data/bam/7B/7B/*_out
```

**Comment by trinidadmartin** [comment] 2021-09-07 14:53
Sure ;)

`snakemake--unlock`
Building DAG of jobs...
Unlocking working directory.
[1]+  Done(1)                 snakemake -C echo_run=1 mode=s enable_callers="['manta','delly','lumpy','gridss']" --use-conda --latency-wait 30 --jobs 14 --cluster "xenon scheduler $SCH --location local:// submit --name smk.{rule} --inherit-env --cores-per-task {threads} --max-run-time 1 --max-memory {resources.mem_mb} --working-directory . --stderr stderr-%j.log --stdout stdout-%j.log" >&smk.log

`rm -r data/bam/10C/*_out`
rm: data/bam/10C/*_out: No such file or directory

`rm -r data/bam/7B/*_out`
rm: data/bam/7B/*_out: No such file or directory

There is nothing created in the folders with the extension _out


`snakemake -np`
Building DAG of jobs...
Job counts:
	count	jobs
	1	all
	2	delly_merge
	10	delly_s
	2	gridss_s
	2	lumpy_s
	2	manta_s
	8	survivor_filter
	2	survivor_merge
	29

[Tue Sep  7 16:52:40 2021]
rule delly_s:
    input: data/fasta/S288C_genome.fasta, data/fasta/S288C_genome.fasta.fai, data/bam/7B/7B.bam, data/bam/7B/7B.bam.bai
    output: data/bam/7B/7B/delly_out/delly-DEL.bcf
    jobid: 20
    wildcards: path=data/bam/7B, sample=7B, sv_type=DEL
    resources: mem_mb=8192, tmp_mb=0


        set -x

        OUTDIR="$(dirname "data/bam/7B/7B/delly_out/delly-DEL.bcf")"
        PREFIX="$(basename "data/bam/7B/7B/delly_out/delly-DEL.bcf" .bcf)"
        OUTFILE="${OUTDIR}/${PREFIX}.unfiltered.bcf"

        # run dummy or real job
        if [ "1" -eq "1" ]; then
            echo "data/fasta/S288C_genome.fasta data/fasta/S288C_genome.fasta.fai data/bam/7B/7B.bam data/bam/7B/7B.bam.bai" > "data/bam/7B/7B/delly_out/delly-DEL.bcf"
        else
            # use OpenMP for threaded jobs
            export OMP_NUM_THREADS=1

            # SV calling
            delly call                 -t "DEL"                 -g "data/fasta/S288C_genome.fasta"                 -o "${OUTFILE}"                 -q 1 `# min.paired-end mapping quality`                 -s 9 `# insert size cutoff, DELs only`                                  "data/bam/7B/7B.bam" &&
            # SV quality filtering
            bcftools filter                 -O b `# compressed BCF format`                 -o "data/bam/7B/7B/delly_out/delly-DEL.bcf"                 -i "FILTER == 'PASS'"                 "${OUTFILE}" &&
            # index BCF file
            bcftools index "data/bam/7B/7B/delly_out/delly-DEL.bcf"
        fi
        

[Tue Sep  7 16:52:40 2021]
rule delly_s:
    input: data/fasta/S288C_genome.fasta, data/fasta/S288C_genome.fasta.fai, data/bam/10C/10C.bam, data/bam/10C/10C.bam.bai
    output: data/bam/10C/10C/delly_out/delly-BND.bcf
    jobid: 24
    wildcards: path=data/bam/10C, sample=10C, sv_type=BND
    resources: mem_mb=8192, tmp_mb=0


        set -x

        OUTDIR="$(dirname "data/bam/10C/10C/delly_out/delly-BND.bcf")"
        PREFIX="$(basename "data/bam/10C/10C/delly_out/delly-BND.bcf" .bcf)"
        OUTFILE="${OUTDIR}/${PREFIX}.unfiltered.bcf"

        # run dummy or real job
        if [ "1" -eq "1" ]; then
            echo "data/fasta/S288C_genome.fasta data/fasta/S288C_genome.fasta.fai data/bam/10C/10C.bam data/bam/10C/10C.bam.bai" > "data/bam/10C/10C/delly_out/delly-BND.bcf"
        else
            # use OpenMP for threaded jobs
            export OMP_NUM_THREADS=1

            # SV calling
            delly call                 -t "BND"                 -g "data/fasta/S288C_genome.fasta"                 -o "${OUTFILE}"                 -q 1 `# min.paired-end mapping quality`                 -s 9 `# insert size cutoff, DELs only`                                  "data/bam/10C/10C.bam" &&
            # SV quality filtering
            bcftools filter                 -O b `# compressed BCF format`                 -o "data/bam/10C/10C/delly_out/delly-BND.bcf"                 -i "FILTER == 'PASS'"                 "${OUTFILE}" &&
            # index BCF file
            bcftools index "data/bam/10C/10C/delly_out/delly-BND.bcf"
        fi

**Comment by arnikz** [comment] 2021-09-07 14:58
> There is nothing created in the folders with the extension _out
> `snakemake -np`

Yeah, that's because a _dry run_ doesn't produce anything, it's mainly used for testing (follow README).

**Comment by arnikz** [comment] 2021-09-28 12:54
Hi @TrinidadMartin: May I close this issue?

**Comment by trinidadmartin** [comment] 2021-09-28 14:23
Hi! Still same error, but I do not have more time to look at it so I guess so, you can close it ;)
Thanks!

**Comment by arnikz** [comment] 2021-09-28 14:39
Sorry, I can't reproduce your issue(s) without more details. All works fine according to unit/CI tests.

**Closed as completed by arnikz** 2021-09-28 14:39 UTC
